# Practitioners Main Problems on Data Pre-Processing Stage

*Question*: According to your personal experience, please outline the main problems or difficulties (up to three) faced during each of the seven ML life cycle stages.

*Answer Type*: Text Free

### Necessary Libraries

In [1]:
import pandas as pd
from utils.basic import rename_values
from utils.dataframe import DataframeUtils
from utils.plot import PlotUtils
from utils.bootstrapping import BootstrappingUtils

### Dataframe Initialization

Here we get a formatted Pandas DataFrame from a raw CSV containing the Survey responses. When formatting, we discard unused columns and renames existing ones to more clear names. We created two classes that help us manage this dataframe and create meaningful charts.

In [2]:
dataframe_obj = DataframeUtils(df_path='./data/main_data.csv', sep=';',
                               to_discard_columns_file='./data/unused_columns.txt',
                               to_format_columns_file='./data/formatted_columns.txt')
# dataframe preview
dataframe_obj.df.head()

,ID,Status,Duration,D1_Undergraduation,D1_Specialization,D1_Master,D1_Phd,D1_Courses,D1_Others,D2_Country,...,Q15_Model_Deploy_Production_Monitoring,Q16_Model_Monitor_Aspects_Input_And_Output,Q16_Model_Monitor_Aspects_Interpretability_Output,Q16_Model_Monitor_Aspects_Output_And_Decisions,Q16_Model_Monitor_Aspects_Fairness,Q16_Model_Monitor_Aspects_Others,Q16_Model_Monitor_Aspects_Others_Free,Q17_Automated_Machine_Learning_Tools_Yes_No,Q17_Automated_Machine_Learning_Tools_Yes_Free,Origin
2,31,Completed (31),1317,Economics,-99,M.Sc. in Economics,-99,Data Scientist in Datacamp,-99,Brazil,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,https://ww2.unipark.de/uc/seml/
3,34,Completed (31),854,-99,Management,No,No,No,No,Brazil,...,70,not quoted,not quoted,quoted,not quoted,not quoted,-99,No,-99,-99
4,36,Completed (31),1593,Mathematics,Informatics,MSC Computer Science,PhD computer Science,Vários cursos in Coursera,-99,Brazil,...,60,quoted,not quoted,quoted,not quoted,not quoted,-99,"Yes, Please, specify",Own approach,-99
5,57,Completed (31),4238,Computer Science,Data science specialization,-99,-99,-99,-99,Germany,...,100,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99
6,46,Completed (31),2821,Actuarial Science,Post Graduation in Data Science,M Sc in Data Science -ML models,no Ph D,no other certifications,-99,Brazil,...,80,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99

In [3]:
# For PROFES, we discarded suspended submissions (e.g., remove those who didn't complete the survey).
dataframe_obj.df.drop(dataframe_obj.df[dataframe_obj.df['Status'] == 'Suspended (22)'].index, inplace = True)

In [4]:
# dataframe preview
dataframe_obj.df.head()

,ID,Status,Duration,D1_Undergraduation,D1_Specialization,D1_Master,D1_Phd,D1_Courses,D1_Others,D2_Country,...,Q15_Model_Deploy_Production_Monitoring,Q16_Model_Monitor_Aspects_Input_And_Output,Q16_Model_Monitor_Aspects_Interpretability_Output,Q16_Model_Monitor_Aspects_Output_And_Decisions,Q16_Model_Monitor_Aspects_Fairness,Q16_Model_Monitor_Aspects_Others,Q16_Model_Monitor_Aspects_Others_Free,Q17_Automated_Machine_Learning_Tools_Yes_No,Q17_Automated_Machine_Learning_Tools_Yes_Free,Origin
2,31,Completed (31),1317,Economics,-99,M.Sc. in Economics,-99,Data Scientist in Datacamp,-99,Brazil,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,https://ww2.unipark.de/uc/seml/
3,34,Completed (31),854,-99,Management,No,No,No,No,Brazil,...,70,not quoted,not quoted,quoted,not quoted,not quoted,-99,No,-99,-99
4,36,Completed (31),1593,Mathematics,Informatics,MSC Computer Science,PhD computer Science,Vários cursos in Coursera,-99,Brazil,...,60,quoted,not quoted,quoted,not quoted,not quoted,-99,"Yes, Please, specify",Own approach,-99
5,57,Completed (31),4238,Computer Science,Data science specialization,-99,-99,-99,-99,Germany,...,100,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99
6,46,Completed (31),2821,Actuarial Science,Post Graduation in Data Science,M Sc in Data Science -ML models,no Ph D,no other certifications,-99,Brazil,...,80,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99

### Grounded Theory

Here we get a formatted Pandas DataFrame from an Excel file containing the codes and categorization of our qualitative responses.

In [5]:
qualitative_df = pd.read_excel('./data/Problems on ML Stages/DATA PRE-PROCESSING.xlsx')
qualitative_df.head()

,lfdn,DATA PRE-PROCESSING,TOPIC,CATEGORY
0,31,Too much missing values,MISSING VALUES,DATA
1,36,Data cleaning,DATA CLEANING,DATA
2,46,wich event are we analysing ?,PROBLEM UNDERSTANDING,INPUT
3,53,sort the data,DATA CLEANING,DATA
4,64,Handling disproportional classes of data,INSUFFICIENT DATA,DATA

### Basic Analysis

In [6]:
# get our valid respondents ids
respondents_ids = list(dataframe_obj.df['ID'])
respondents_ids = [int(respondent_id) for respondent_id in respondents_ids]
respondents_ids[:5]

[31, 34, 36, 57, 46]

In [7]:
# discard the ids that are suspended
qualitative_df = qualitative_df[qualitative_df['lfdn'].isin(respondents_ids)][['DATA PRE-PROCESSING', 'TOPIC', 'CATEGORY']]

In [8]:
# get a list with all the reported categories
category_column = list(qualitative_df['CATEGORY'])
category_column[:5]

['DATA', 'DATA', 'INPUT', 'DATA', 'DATA']

In [9]:
# compute the total of answers that belong to each category
total_per_category_df = qualitative_df[['CATEGORY', 'TOPIC']].groupby(['CATEGORY']).count()
total_per_category_df

                TOPIC
CATEGORY
DATA              175
INFRASTRUCTURE     11
INPUT               9
METHOD             36
ORGANIZATION       12
PEOPLE              1

In [10]:
# get the total of qualitative answers
total_answers = total_per_category_df['TOPIC'].sum()
print(f'The total of qualitative answers to be considered is {total_answers}')

The total of qualitative answers to be considered is 244

In [11]:
# we create two lists that contain, for each category, the total of qualitative answers and their percentage
category_percentage = []
category_total = []
# note that we will have repeated values, once we are creating lists with the same length of the column 'CATEGORY' in the qualitative dataframe
for category in category_column:
    category_percentage.append(round(total_per_category_df.loc[category]['TOPIC'] / total_answers * 100, 2))
    category_total.append(total_per_category_df.loc[category]['TOPIC'])

In [12]:
# include two new columns to our qualitative dataframe
qualitative_df['CATEGORY_TOTAL'] = category_total
qualitative_df['CATEGORY_%'] = category_percentage
qualitative_df.head()

,DATA PRE-PROCESSING,TOPIC,CATEGORY,CATEGORY_TOTAL,CATEGORY_%
0,Too much missing values,MISSING VALUES,DATA,175,71.72
1,Data cleaning,DATA CLEANING,DATA,175,71.72
2,wich event are we analysing ?,PROBLEM UNDERSTANDING,INPUT,9,3.69
3,sort the data,DATA CLEANING,DATA,175,71.72
4,Handling disproportional classes of data,INSUFFICIENT DATA,DATA,175,71.72

In [13]:
# now we group our results considering the category and the topic
qualitative_df = qualitative_df.groupby(['CATEGORY', 'CATEGORY_TOTAL', 'CATEGORY_%', 'TOPIC']).count()

In [14]:
# rename the remaining column, which is now a simple count representing the quantity of each category and topic
qualitative_df.columns = ['QUANTITY']
# add the percentage version of each quantity to improve readability
qualitative_df['QUANTITY_%'] = round(qualitative_df['QUANTITY'] / qualitative_df['QUANTITY'].sum() * 100, 2)
qualitative_df

                                                                                           QUANTITY  \
CATEGORY       CATEGORY_TOTAL CATEGORY_% TOPIC
DATA           175            71.72      DATA ACCESS NOT ALLOWED OR HARD TO GET                   1
                                         DATA ACCESSIBILITY                                       6
                                         DATA CLEANING                                           24
                                         DATA COMPLEXITY                                          2
                                         DATA MANAGEMENT                                          1
                                         DATA QUALITY                                            53
                                         DATA UNDERSTANDING                                      17
                                         DATA VERSIONING                                          2
                                         DEALING WITH OUTLIERS                                    6
                                         GDPR AND/OR OTHER LAW RESTRICTIONS                       4
                                         INSUFFICIENT DATA                                       15
                                         LARGE DATA VOLUME                                        6
                                         MERGE DATA FROM DIFFERENT SOURCES AND FORMATS           26
                                         MISSING VALUES                                          12
INFRASTRUCTURE 11             4.51       COMPUTATIONAL CONSTRAINTS                                8
                                         PROCESSING TIME                                          2
                                         TOOLS AVAILABLE                                          1
INPUT          9              3.69       BUSINESS/DOMAIN UNDERSTANDING                            6
                                         PROBLEM UNDERSTANDING                                    2
                                         SCOPE DEFINITION                                         1
METHOD         36             14.75      BAD PREPROCESSING                                        3
                                         BUILD PIPELINES                                          7
                                         CODE QUALITY                                             1
                                         DATA AUGMENTATION                                        2
                                         DATA COLLECTION ERRORS                                   1
                                         DATA SCIENCE COMPLEXITY                                  1
                                         DEALING WITH BIAS                                        1
                                         DEALING WITH NOISE                                       1
                                         DEALING WITH OUTLIERS                                    1
                                         FEATURE ENGINEERING                                      8
                                         GUIDELINES                                               1
                                         HOW TO CHOOSE BEST TECHNIQUE                             1
                                         NEED OF PREPROCESSING AGAIN                              1
                                         PREPROCESSING COST                                       1
                                         PROGRAMING EFFORT                                        2
                                         REDUCE DIMENSIONALITY                                    1
                                         TASK COMPLEXITY                                          1
                                         TASK COMPLEXITY                                          1
                                         TREATING SPECIFICITY                                     1
ORGANIZATION   12             4.92       DEAL WITH MULTIDISCIPLINARY TEAM                         1
                                         FINANCIAL ISSUES                                         1
                                         LACK OF TALENT/SKILL                                     2
                                         LACK OF TIME                                             6
                                         LOW CLIENT/DOMAIN EXPERT AVAILABILITY/ENGAGEMENT         1
                                         TEAM MANAGEMENT                                          1
PEOPLE         1              0.41       LACK OF DATA SCIENCE KNOWLEDGE                           1

                                                                                           QUANTITY_%
CATEGORY       CATEGORY_TOTAL CATEGORY_% TOPIC
DATA           175            71.72      DATA ACCESS NOT ALLOWED OR HARD TO GET                  0.41
                                         DATA ACCESSIBILITY                                      2.46
                                         DATA CLEANING                                           9.84
                                         DATA COMPLEXITY                                         0.82
                                         DATA MANAGEMENT                                         0.41
                                         DATA QUALITY                                           21.72
                                         DATA UNDERSTANDING                                      6.97
                                         DATA VERSIONING                                         0.82
                                         DEALING WITH OUTLIERS                                   2.46
                                         GDPR AND/OR OTHER LAW RESTRICTIONS                      1.64
                                         INSUFFICIENT DATA                                       6.15
                                         LARGE DATA VOLUME                                       2.46
                                         MERGE DATA FROM DIFFERENT SOURCES AND FORMATS          10.66
                                         MISSING VALUES                                          4.92
INFRASTRUCTURE 11             4.51       COMPUTATIONAL CONSTRAINTS                               3.28
                                         PROCESSING TIME                                         0.82
                                         TOOLS AVAILABLE                                         0.41
INPUT          9              3.69       BUSINESS/DOMAIN UNDERSTANDING                           2.46
                                         PROBLEM UNDERSTANDING                                   0.82
                                         SCOPE DEFINITION                                        0.41
METHOD         36             14.75      BAD PREPROCESSING                                       1.23
                                         BUILD PIPELINES                                         2.87
                                         CODE QUALITY                                            0.41
                                         DATA AUGMENTATION                                       0.82
                                         DATA COLLECTION ERRORS                                  0.41
                                         DATA SCIENCE COMPLEXITY                                 0.41
                                         DEALING WITH BIAS                                       0.41
                                         DEALING WITH NOISE                                      0.41
                                         DEALING WITH OUTLIERS                                   0.41
                                         FEATURE ENGINEERING                                     3.28
                                         GUIDELINES                                              0.41
                                         HOW TO CHOOSE BEST TECHNIQUE                            0.41
                                         NEED OF PREPROCESSING AGAIN                             0.41
                                         PREPROCESSING COST                                      0.41
                                         PROGRAMING EFFORT                                       0.82
                                         REDUCE DIMENSIONALITY                                   0.41
                                         TASK COMPLEXITY                                         0.41
                                         TASK COMPLEXITY                                         0.41
                                         TREATING SPECIFICITY                                    0.41
ORGANIZATION   12             4.92       DEAL WITH MULTIDISCIPLINARY TEAM                        0.41
                                         FINANCIAL ISSUES                                        0.41
                                         LACK OF TALENT/SKILL                                    0.82
                                         LACK OF TIME                                            2.46
                                         LOW CLIENT/DOMAIN EXPERT AVAILABILITY/ENGAGEMENT        0.41
                                         TEAM MANAGEMENT                                         0.41
PEOPLE         1              0.41       LACK OF DATA SCIENCE KNOWLEDGE                          0.41